spring.application.name=subjects-loader

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/blacklistsdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/changelog.xml

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

spring.profiles.active=test

job.cron-expression =*/10 * * * * *

rest.search-url=http://www.cbr.ru/warninglistapi/Search
rest.detail-info-url=http://www.cbr.ru/warninglistapi/DetailInfo?id=